### PR TITLE
Configure test metadata collection

### PR DESCRIPTION
**Pull request by sd-kin**
CircleCI still throwing alert about test metadata witch don't collect automaticllly fore this project. It will gone after merging, if I wright.

### CODE REVIEW

**Comment by kirushik** [comment]
Are you sure that those custom test steps in `circle.yml` are absolutely needed?

**Comment by kirushik** [comment]
Because in my projects I never required those lines.

**Comment by sd-kin** [comment]
No, I don't sure, but it's part of instruction. Maybe it nedeed for custom configured test or something. Don't understend what exactly I'm doing in this step, it bothering me a little.

**Comment by kirushik** [comment]
Looks good to merge, :ship:

**Pull request merged**
